name: Build and Deploy Fiber

on:
  push:
    branches:
      - main

jobs:
  # -------------------------
  # 1. Checkout & Test
  # -------------------------
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.25

      - name: Run tests
        run: go test ./...

  # -------------------------
  # 2. Build & Push Docker Image
  # -------------------------
  build-and-push:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Calculate source hash
        id: hash
        run: |
          # Only main folders in grep ...
          src_hash=$(git ls-tree -r HEAD --name-only \
            | grep -E '^(cmd|pkg|api)/' \
            | sort \
            | xargs cat \
            | sha1sum \
            | awk '{print $1}')
          echo "SRC_HASH=$src_hash" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            dembyvlad/micro-fiber-pet:${{ env.SRC_HASH }}
            dembyvlad/micro-fiber-pet:latest

  # -------------------------
  # 3. Deploy to VPS
  # -------------------------
  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Deploy on VPS
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /opt/
            devbox shell
            task deploy:fiber
